apiVersion: v1
data:
  MONGO_HOST: bW9uZ28= #mongo
  MONGO_USER: YWRtaW51c2Vy #adminuser
  MONGO_PASSWORD: cGFzc3dvcmQxMjM= #password123
  MONGO_PORT: MjcwMTc= #27017
  NODE_ENV: cHJvZHVjdGlvbg== #production
  PORT: OTAwMQ== #9001
  JWT_SECRET: TU1TTUNtbWFjazJAa2tzbik5MmssQW0/LjIkJA== #MMSMCmmack2@kksn)92k,Am?.2$$
  JWT_ACCESS_EXPIRATION_MINUTES: NQ== #5
  JWT_REFRESH_EXPIRATION_DAYS: MQ== #1
kind: Secret
metadata:
  creationTimestamp: null
  name: secrets
