apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
    nodePort: 32000
  selector:
    app: backend
  type: LoadBalancer